import './globals.css'

export const metadata = {
	title: "Piscina di Agordo",
	description: "Generated by create next app",
	icons: { icon: "/favicon-32x32.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<head />
			<body>{children}</body>
		</html>
  );
}
