import './globals.css'

export const meta = {
	title: "Piscina di Agordo",
	description: "Generated by create next app",
	favicon: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<head />
			<body>{children}</body>
		</html>
  );
}
